### ISSUE TITLE
Crash on aync

### ISSUE THREAD

**Issue by superLei** [ViscousPotential/GitSync#9]
Model: Galaxy S23
Ram/Rom: 8/256GB
Android: 14
App Version: v1.301
Logs:
App logs are attached! 
 RecentCommits: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.eclipse.jgit.lib.AnyObjectId.hashCode()' on a null object reference
 at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:115)
 at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:76)
 at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:31)
 at org.eclipse.jgit.internal.storage.file.LooseObjects.hasCached(LooseObjects.java:99)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:359)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:350)
 at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:133)
 at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
 at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1117)
 at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:1028)
 at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:278)
 at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:495)
 at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:421)
 at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:210)
 at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
 at android.app.Activity.performResume(Activity.java:9134)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
 at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:230)
 at android.os.Looper.loop(Looper.java:319)
 at android.app.ActivityThread.main(ActivityThread.java:8919)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.eclipse.jgit.lib.AnyObjectId.hashCode()' on a null object reference
 at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:115)
 at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:76)
 at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:31)
 at org.eclipse.jgit.internal.storage.file.LooseObjects.hasCached(LooseObjects.java:99)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:359)
 at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:350)
 at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:133)
 at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
 at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1117)
 at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:1028)
 at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:278)
 at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:495)
 at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:421)
 at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:210)
 at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
 at android.app.Activity.performResume(Activity.java:9134)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
 at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:230)
 at android.os.Looper.loop(Looper.java:319)
 at android.app.ActivityThread.main(ActivityThread.java:8919)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
 
 Android Version: 14 (SDK: 34) 
 Device Model: samsung SM-S9110

**Comment by ViscousPot** [comment]
This seems like it might be to do with having a differently named master branch. Can you confirm?
If so, it should be fixed in the newer versions of the app. If not please let me know and I will look into it

**Comment by superLei** [comment]
> This seems like it might be to do with having a differently named master branch. Can you confirm? If so, it should be fixed in the newer versions of the app. If not please let me know and I will look into it

The branch name of my repo is "main", and i solved the problem by clearing app's data and reopening the app. But there is a other issue: It's always in git clone state when synchronizing my repo

**Comment by ViscousPot** [comment]
Right yeah, older versions had trouble with `main`
Can you elaborate on what `in git clone state` means? Maybe share a screenshot if possible
:)

**Comment by superLei** [comment]
> Right yeah, older versions had trouble with `main` Can you elaborate on what `in git clone state` means? Maybe share a screenshot if possible :)

![4851726019504_ pic](https://github.com/user-attachments/assets/2c22b2d5-d280-45db-9054-20c52710468a)

**Comment by ViscousPot** [comment]
Hey, did you end up getting this working? The clone repo page screenshot that you shared looks like normal app behaviour. The first clone can take some time on the first time around.
If you really think it's lasting forever, can you try making sure that there are files in your repo and that it is not bare? If this is the fix, can you let me know 🙏 
Please update to the latest version before trying again as I am trying to improve the app

**Comment by ViscousPot** [comment]
Closing since no response
